baseURL: 'https://pimsnel.com'
languageCode: en-us
title: Pim Snel
theme: pimsnelcom
params:
  subTitle: Bothered by ideas
  domain: pimsnel.com
  description: >-
    Pim Snel is a creative technophile, IT-consultant and software developer,
    interested in nature, food, and creating and consuming open source software
    for business and fun.
  description2: >-
    I am a creative technophile, IT-consultant and software developer,
    interested in nature, food, and creating and consuming open source software
    for business and fun.
  siteImage: 'https://pimsnel.com/screenshot.jpg'
  aboutText: >
    ### Hello


    Thanks for visiting my site.


    I'm a digital family man. I live in the center of the Netherlands, just at
    the spot where two main rivers kiss eachother. I make wine, cider and bread.
    I like old tractors, Land Rovers, timbering and being outside with my dog.


    I founded my first company Lingewoud in 2000 and sold it in 2021. I now

    work as independant IT-consultant and software developer. I will propably

    be founding a new company within one or two years.


    This site links to several online places where I post writings or source
    code.


    You can also check out my [LinkedIn](https://linkedin.com/in/pimsnel) and my
    [Github](https://github.com/mipmip).
