hugover: 0.88.1
serve:
  - key: default
    config: config.yaml
build:
  - key: default
    config: config.yaml
menu:
  - key: content
    title: Content
    menuItems:
      - key: frontpage
      - key: pages
  - key: settings
    title: Settings
    menuItems:
      - key: mainConfig
singles:
  - key: frontpage
    title: Front Page
    file: content/_index.md
    _mergePartial: page
  - key: mainConfig
    title: Site Configuration
    file: config.yaml
    fields:
      - key: title
        title: Site Title
        type: string
        tip: Your page title.
      - key: baseURL
        title: Base URL
        type: string
        tip: Your site URL.
      - key: theme
        title: Theme
        type: readonly
        tip: The current theme.
      - key: languageCode
        title: Language Code
        type: readonly
      - key: googleAnalytics
        title: Google Analytics
        type: string
        tip: Provide a Google Analitics Tracking Code to enable analytics.
      - key: enableRobotsTXT
        title: Enable Robots
        type: boolean
        default: true
        tip: 'If you want you page to be indexed, keep this enabled.'
